name: mason
description: >
  A template generator which helps you lay the foundation for your next project.
# After changing the version, run `pub run build_runner build`.
version: 0.0.1+1
homepage: https://github.com/felangel/mason

environment:
  sdk: ">=2.8.1 <3.0.0"

executables:
  mason:
